name: www.softapalvelin.com
favicon: null
layout_spectrum: 0.3975385050289333
typography_spectrum: 0.8609273212496191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#4285f4'
    - '#8ab3f4'
    - '#cf6f1f'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
